#version: 2
#updates:
#  - package-ecosystem: "nuget" # See documentation for possible values
#    directory: "/Rinkudesu.Gateways.Webui" # Location of package manifests
#    schedule:
#      interval: "monthly"

#  - package-ecosystem: "github-actions"
#    directory: "/"
#    schedule:
      # Check for updates to GitHub Actions every weekday
#      interval: "monthly"
