version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/Rinkudesu.Services.Links" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
    - dependency-name: Microsoft.AspNetCore.Authentication.OpenIdConnect
    - dependency-name: Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation
