version: 3

services:
  rinkudesu-webui:
    image: ghcr.io/rinkudesu/rinkudesu-webui:latest
    ports:
      - "127.0.0.1:9876:80"
    environment:
      RINKUDESU_CLIENTID: "rinkudesu"
      RINKUDESU_LINKS: "https://<hostname-of-links-microservice>/api/"
      RINKUDESU_IDENTITY: "http://<hostname-of-identity-ms>/api/"
      RINKU_KAFKA_ADDRESS: "<hostname-of-kafka>:9092"
      RINKU_KAFKA_CLIENT_ID: "rinkudesu-webui"
      RINKU_KAFKA_CONSUMER_GROUP_ID: "rinkudesu-webui"
