version: '3'

services:
  postgres:
      image: postgres
      restart: unless-stopped
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak
      restart: unless-stopped
      environment:
        KC_HOSTNAME: localhost
        KC_DB: postgres
        KC_DB_PASSWORD: password
        KC_DB_URL: jdbc:postgresql://postgres/keycloak
        KC_DB_USERNAME: keycloak
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
      volumes:
        - ./keycloakImports:/opt/keycloak/data/import
      ports:
        - 8080:8080
      depends_on:
        - postgres
      command: start-dev --import-realm
